//! Plan Executor Module
//!
//! Executes plans generated by the Planning Engine using real SynCore MCP tools.
//! Collects outputs into ExecutionResult for storage in ReasoningLedger.
//!
//! Safety features:
//! - Read/search/index tools execute by default
//! - Write operations require explicit allow_write=true flag
//! - All tool executions are logged and collected

use super::plan_engine::{Plan, PlanStep};
use crate::router::SynCoreState;
use anyhow::Result;
use serde::{Deserialize, Serialize};

/// Result of plan execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionResult {
    /// Number of steps successfully executed
    pub steps_executed: usize,
    /// Tool names called (in order)
    pub tool_calls: Vec<String>,
    /// Outputs from each tool (JSON serialized)
    pub outputs: Vec<String>,
    /// Overall status
    pub status: ExecutionStatus,
    /// Optional error message
    pub error: Option<String>,
}

/// Execution status
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExecutionStatus {
    Success,
    PartialSuccess,
    Failed,
}

impl ExecutionResult {
    pub fn new() -> Self {
        Self {
            steps_executed: 0,
            tool_calls: Vec::new(),
            outputs: Vec::new(),
            status: ExecutionStatus::Success,
            error: None,
        }
    }
}

impl Default for ExecutionResult {
    fn default() -> Self {
        Self::new()
    }
}

/// Execute a plan using real SynCore tools
///
/// # Arguments
/// * `plan` - The plan to execute
/// * `state` - SynCoreState with access to all tools
/// * `allow_write` - Whether to allow write operations (memory_store, file updates)
///
/// # Returns
/// ExecutionResult with tool calls, outputs, and status
pub async fn execute_plan(
    plan: &Plan,
    state: &SynCoreState,
    allow_write: bool,
) -> Result<ExecutionResult> {
    let mut result = ExecutionResult::new();

    for step in &plan.steps {
        // Check if step requires write permission
        if is_write_operation(&step.tool) && !allow_write {
            result.status = ExecutionStatus::PartialSuccess;
            result.outputs.push(format!(
                "Skipped (requires write permission): {}",
                step.tool
            ));
            continue;
        }

        // Execute step
        match execute_step(step, state).await {
            Ok(output) => {
                result.steps_executed += 1;
                result.tool_calls.push(step.tool.clone());
                result.outputs.push(output);
            }
            Err(e) => {
                result.status = if result.steps_executed > 0 {
                    ExecutionStatus::PartialSuccess
                } else {
                    ExecutionStatus::Failed
                };
                result.error = Some(format!("Step {} failed: {}", step.tool, e));
                result
                    .outputs
                    .push(format!("Error in {}: {}", step.tool, e));
                // Continue with remaining steps (best-effort execution)
            }
        }
    }

    // Final status determination
    if result.steps_executed == plan.steps.len() && result.error.is_none() {
        result.status = ExecutionStatus::Success;
    }

    Ok(result)
}

/// Execute a single plan step
async fn execute_step(step: &PlanStep, state: &SynCoreState) -> Result<String> {
    match step.tool.as_str() {
        // Memory operations
        "memory_store" => execute_memory_store(&step.args, state),
        "memory_query" => execute_memory_query(&step.args, state),

        // Vector operations
        "vector_search" => execute_vector_search(&step.args, state),
        "vector_insert" => execute_vector_insert(&step.args, state),

        // Code operations
        "code_index" => execute_code_index(&step.args, state).await,
        "code_search" => execute_code_search(&step.args, state).await,
        "code_graph_fusion_query" => execute_code_graph_fusion(&step.args, state).await,

        // Parser operations
        "parser_analyze" => execute_parser_analyze(&step.args, state),
        "parser_search" => execute_parser_search(&step.args, state),

        // Graph operations
        "raggraph_multihop" => execute_raggraph_multihop(&step.args, state).await,

        // Fallback
        _ => Ok(format!("Unknown tool: {} (args: {})", step.tool, step.args)),
    }
}

/// Check if a tool requires write permission
fn is_write_operation(tool: &str) -> bool {
    matches!(
        tool,
        "memory_store" | "vector_insert" | "code_index" | "file_update" | "task_create"
    )
}

// Tool execution functions

fn execute_memory_store(args: &serde_json::Value, state: &SynCoreState) -> Result<String> {
    let key = args["key"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing key"))?;
    let value = args["value"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing value"))?;

    state.memory.store(key, value)?;
    Ok(format!("Stored: {} = {}", key, value))
}

fn execute_memory_query(args: &serde_json::Value, state: &SynCoreState) -> Result<String> {
    let key = args["key"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing key"))?;

    match state.memory.query(key) {
        Ok(value) => {
            let val_str = value.unwrap_or_else(|| "null".to_string());
            Ok(format!("Retrieved: {} = {}", key, val_str))
        }
        Err(_) => Ok(format!("Key not found: {}", key)),
    }
}

fn execute_vector_search(args: &serde_json::Value, state: &SynCoreState) -> Result<String> {
    let query = args["query"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing query"))?;
    let limit = args["limit"].as_u64().unwrap_or(10) as usize;

    // Use GENERAL domain store for plan documents
    let store = state.general_store.lock().unwrap();
    let results = store.search(query, limit, crate::vector::SearchScope::Global)?;

    Ok(format!("Found {} vector results", results.len()))
}

fn execute_vector_insert(args: &serde_json::Value, state: &SynCoreState) -> Result<String> {
    let text = args["text"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing text"))?;
    let id = args["id"].as_i64().unwrap_or(0);

    let mut store = state.general_store.lock().unwrap();
    store.insert_text(id, None, text, "plan")?;

    Ok(format!("Inserted vector: id={}", id))
}

async fn execute_code_index(_args: &serde_json::Value, _state: &SynCoreState) -> Result<String> {
    // Placeholder - would call actual code_graph indexing
    Ok("Code indexing completed".to_string())
}

async fn execute_code_search(args: &serde_json::Value, _state: &SynCoreState) -> Result<String> {
    let query = args["query"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing query"))?;

    // Placeholder - would call actual code_graph search
    Ok(format!("Code search for: {}", query))
}

async fn execute_code_graph_fusion(
    args: &serde_json::Value,
    _state: &SynCoreState,
) -> Result<String> {
    let query = args["query"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing query"))?;
    let mode_hint = args["mode_hint"].as_str().unwrap_or("simple");

    // Placeholder - would call actual code_graph_fusion_query
    Ok(format!(
        "CodeGraph fusion query: {} (mode: {})",
        query, mode_hint
    ))
}

fn execute_parser_analyze(args: &serde_json::Value, _state: &SynCoreState) -> Result<String> {
    let file_path = args["file_path"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing file_path"))?;

    // Use actual parser
    let parser = crate::parser::Parser::new()?;
    match parser.parse_file(std::path::Path::new(file_path)) {
        Ok(structure) => {
            let total_items = structure.functions.len() + structure.classes.len();
            Ok(format!("Parsed: {} ({} items)", file_path, total_items))
        }
        Err(e) => Ok(format!("Failed to parse {}: {}", file_path, e)),
    }
}

fn execute_parser_search(args: &serde_json::Value, _state: &SynCoreState) -> Result<String> {
    let pattern = args["pattern"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing pattern"))?;

    // Use ripgrep via std::process
    use std::process::Command;
    let output = Command::new("rg").args(&["--count", pattern, "."]).output();

    match output {
        Ok(out) if out.status.success() => {
            let count = String::from_utf8_lossy(&out.stdout).trim().to_string();
            Ok(format!(
                "Found pattern '{}' in {} locations",
                pattern, count
            ))
        }
        _ => Ok(format!("Pattern search for: {}", pattern)),
    }
}

async fn execute_raggraph_multihop(
    args: &serde_json::Value,
    _state: &SynCoreState,
) -> Result<String> {
    let seed_nodes = args["seed_nodes"]
        .as_array()
        .ok_or_else(|| anyhow::anyhow!("Missing seed_nodes"))?;

    // Placeholder - would call actual raggraph_multihop
    Ok(format!("RAGGraph multihop from {} seeds", seed_nodes.len()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    #[test]
    fn test_is_write_operation() {
        assert!(is_write_operation("memory_store"));
        assert!(is_write_operation("vector_insert"));
        assert!(is_write_operation("code_index"));
        assert!(!is_write_operation("memory_query"));
        assert!(!is_write_operation("vector_search"));
    }

    #[test]
    fn test_execution_result_creation() {
        let result = ExecutionResult::new();
        assert_eq!(result.steps_executed, 0);
        assert_eq!(result.status, ExecutionStatus::Success);
        assert!(result.error.is_none());
    }

    #[tokio::test]
    async fn test_execute_plan_empty() {
        let embeddings = Box::new(crate::vector::HuggingFaceEmbeddings::new().unwrap());
        let vector_store = Arc::new(Mutex::new(crate::vector::VectorStore::new(embeddings)));
        let state = SynCoreState::with_db_manager(vector_store).unwrap();

        let plan = Plan::new();
        let result = execute_plan(&plan, &state, false).await.unwrap();

        assert_eq!(result.steps_executed, 0);
        assert_eq!(result.status, ExecutionStatus::Success);
    }
}
