//! LLM Adapter for Tree-of-Thought Reasoning
//!
//! Converts ReasoningNodeContext to LLM prompts and parses LLM output
//! into ThoughtNode drafts for ToT expansion.

use crate::llm::{Completion, LanguageModel, Prompt};
use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use serde_json;

/// Draft of a thought node generated by LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThoughtNodeDraft {
    /// Text content of the thought
    pub text: String,
    /// Confidence score (0.0 to 1.0)
    pub confidence: f64,
}

/// Builds LLM prompts from reasoning context
pub struct PromptBuilder;

impl PromptBuilder {
    /// Build ToT expansion prompt from node context
    ///
    /// Creates a comprehensive prompt including reasoning history,
    /// current node, and instructions for generating thought branches.
    pub fn build_tot_prompt(context: &crate::reasoning::ReasoningNodeContext) -> String {
        let mut prompt = String::new();

        // System instructions
        prompt
            .push_str("You are a reasoning assistant helping to explore multiple thought paths.\n");
        prompt.push_str(
            "Given the current reasoning context, generate 3-5 distinct thought branches.\n",
        );
        prompt.push_str("Each branch should represent a different approach or perspective.\n");
        prompt.push_str("Respond with JSON format: {\"thoughts\": [{\"text\": \"...\", \"confidence\": 0.9}, ...]}\n\n");

        // Session context
        prompt.push_str(&format!("Session ID: {}\n\n", context.session_id));

        // Reasoning path (history)
        if !context.path.is_empty() {
            prompt.push_str("Reasoning History:\n");
            for (i, node) in context.path.iter().enumerate() {
                prompt.push_str(&format!("{}. {}\n", i + 1, node.content));
            }
            prompt.push_str("\n");
        }

        // Current node
        prompt.push_str(&format!("Current Thought: {}\n\n", context.node.content));

        // Existing branches (if any)
        if !context.children.is_empty() {
            prompt.push_str("Existing Branches (already explored):\n");
            for (i, child) in context.children.iter().enumerate() {
                prompt.push_str(&format!("{}. {}\n", i + 1, child.content));
            }
            prompt.push_str("\n");
        }

        // Instructions for expansion
        prompt.push_str("Generate new thought branches that explore different approaches:\n");
        prompt.push_str("- Consider alternative strategies\n");
        prompt.push_str("- Explore edge cases or constraints\n");
        prompt.push_str("- Suggest refinements to current approach\n");
        prompt.push_str("- Provide confidence scores (0.0-1.0) based on feasibility\n\n");

        prompt.push_str("Respond only with the JSON format specified above.");

        prompt
    }

    /// Create LLM Prompt struct from reasoning context
    pub fn create_prompt(context: &crate::reasoning::ReasoningNodeContext) -> Prompt {
        let system_prompt = "You are a reasoning assistant for Tree-of-Thought exploration.";
        let user_prompt = Self::build_tot_prompt(context);

        Prompt::new(system_prompt, user_prompt)
            .with_temperature(0.7) // Creative but focused
            .with_max_tokens(1024) // Reasonable limit for thought branches
    }
}

/// Parses LLM output into ThoughtNode drafts
pub struct LLMOutputParser;

impl LLMOutputParser {
    /// Parse completion response into thought node drafts
    ///
    /// Extracts JSON from completion text and converts to ThoughtNodeDraft structs.
    pub fn parse_thoughts(completion: &Completion) -> Result<Vec<ThoughtNodeDraft>> {
        // Try to extract JSON from completion text
        let json_text = Self::extract_json(&completion.text)?;

        // Parse JSON
        let parsed: serde_json::Value =
            serde_json::from_str(&json_text).map_err(|e| anyhow!("Failed to parse JSON: {}", e))?;

        // Extract thoughts array
        let thoughts = parsed
            .get("thoughts")
            .and_then(|v| v.as_array())
            .ok_or_else(|| anyhow!("Response missing 'thoughts' array"))?;

        // Convert to ThoughtNodeDraft structs
        let mut drafts = Vec::new();
        for (i, thought) in thoughts.iter().enumerate() {
            let text = thought
                .get("text")
                .and_then(|v| v.as_str())
                .ok_or_else(|| anyhow!("Thought {} missing 'text' field", i))?
                .to_string();

            let confidence = thought
                .get("confidence")
                .and_then(|v| v.as_f64())
                .ok_or_else(|| anyhow!("Thought {} missing 'confidence' field", i))?;

            // Validate confidence range
            if confidence < 0.0 || confidence > 1.0 {
                return Err(anyhow!("Thought {} has invalid confidence: {}", i, confidence));
            }

            drafts.push(ThoughtNodeDraft {
                text,
                confidence,
            });
        }

        if drafts.is_empty() {
            return Err(anyhow!("No thoughts found in LLM response"));
        }

        // Validate reasonable number of thoughts
        if drafts.len() > 10 {
            return Err(anyhow!("Too many thoughts returned: {}", drafts.len()));
        }

        Ok(drafts)
    }

    /// Extract JSON from potentially wrapped text
    ///
    /// Handles cases where LLM returns text before/after JSON.
    fn extract_json(text: &str) -> Result<String> {
        // Look for JSON object start and end
        let start = text.find('{').ok_or_else(|| anyhow!("No JSON object start found"))?;
        let end = text.rfind('}').ok_or_else(|| anyhow!("No JSON object end found"))?;

        if start >= end {
            return Err(anyhow!("Invalid JSON bounds"));
        }

        let json_text = &text[start..=end];

        // Validate that it looks like JSON
        if !json_text.contains("\"thoughts\"") {
            return Err(anyhow!("JSON doesn't contain 'thoughts' field"));
        }

        Ok(json_text.to_string())
    }

    /// Validate thought draft quality
    pub fn validate_draft(draft: &ThoughtNodeDraft) -> Result<()> {
        if draft.text.trim().is_empty() {
            return Err(anyhow!("Thought text cannot be empty"));
        }

        if draft.text.len() > 1000 {
            return Err(anyhow!("Thought text too long: {} chars", draft.text.len()));
        }

        if draft.confidence < 0.0 || draft.confidence > 1.0 {
            return Err(anyhow!("Invalid confidence: {}", draft.confidence));
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::databases::cognition_graph::ThoughtNodeProperties;
    use crate::llm::Completion;
    use crate::reasoning::ReasoningNodeContext;

    fn create_test_context() -> ReasoningNodeContext {
        let node = ThoughtNodeProperties {
            id: "test_node".to_string(),
            session_id: "test_session".to_string(),
            parent_id: Some("parent_node".to_string()),
            step_index: 2,
            content: "Current approach: Use recursive algorithm".to_string(),
            score: Some(0.8),
        };

        let parent = ThoughtNodeProperties {
            id: "parent_node".to_string(),
            session_id: "test_session".to_string(),
            parent_id: None,
            step_index: 1,
            content: "Problem: Need to process tree structure".to_string(),
            score: Some(0.9),
        };

        ReasoningNodeContext::from_properties(
            node,
            "test_session".to_string(),
            vec![parent],
            Vec::new(),
        )
    }

    #[test]
    fn test_prompt_builder_creates_valid_prompt() {
        let context = create_test_context();
        let prompt = PromptBuilder::build_tot_prompt(&context);

        assert!(prompt.contains("Session ID: test_session"));
        assert!(prompt.contains("Current Thought: Current approach: Use recursive algorithm"));
        assert!(prompt.contains("Reasoning History:"));
        assert!(prompt.contains("Problem: Need to process tree structure"));
        assert!(prompt.contains("JSON format"));
        assert!(prompt.contains("\"thoughts\""));
    }

    #[test]
    fn test_prompt_builder_creates_prompt_struct() {
        let context = create_test_context();
        let prompt = PromptBuilder::create_prompt(&context);

        assert_eq!(prompt.system, "You are a reasoning assistant for Tree-of-Thought exploration.");
        assert!(prompt.user.contains("Current approach: Use recursive algorithm"));
        assert_eq!(prompt.temperature, Some(0.7));
        assert_eq!(prompt.max_tokens, Some(1024));
    }

    #[test]
    fn test_json_extraction() {
        let valid_json = r#"Some text before {"thoughts": [{"text": "test", "confidence": 0.8}]} some text after"#;
        let extracted = LLMOutputParser::extract_json(valid_json).unwrap();

        assert_eq!(extracted, r#"{"thoughts": [{"text": "test", "confidence": 0.8}]}"#);
    }

    #[test]
    fn test_json_extraction_invalid() {
        let no_json = "No JSON here";
        assert!(LLMOutputParser::extract_json(no_json).is_err());

        let incomplete_json = r#"{"thoughts": [{"text": "test""#;
        assert!(LLMOutputParser::extract_json(incomplete_json).is_err());
    }

    #[test]
    fn test_parse_thoughts_valid() {
        let completion = Completion::new(
            r#"{"thoughts": [
            {"text": "Continue with recursion", "confidence": 0.9},
            {"text": "Try iterative approach", "confidence": 0.7}
        ]}"#,
        );

        let drafts = LLMOutputParser::parse_thoughts(&completion).unwrap();
        assert_eq!(drafts.len(), 2);
        assert_eq!(drafts[0].text, "Continue with recursion");
        assert_eq!(drafts[0].confidence, 0.9);
        assert_eq!(drafts[1].text, "Try iterative approach");
        assert_eq!(drafts[1].confidence, 0.7);
    }

    #[test]
    fn test_parse_thoughts_invalid() {
        // Missing thoughts array
        let completion = Completion::new(r#"{"not_thoughts": []}"#);
        assert!(LLMOutputParser::parse_thoughts(&completion).is_err());

        // Invalid confidence
        let completion = Completion::new(
            r#"{"thoughts": [
            {"text": "test", "confidence": 1.5}
        ]}"#,
        );
        assert!(LLMOutputParser::parse_thoughts(&completion).is_err());

        // Empty thoughts
        let completion = Completion::new(r#"{"thoughts": []}"#);
        assert!(LLMOutputParser::parse_thoughts(&completion).is_err());
    }

    #[test]
    fn test_draft_validation() {
        let valid_draft = ThoughtNodeDraft {
            text: "Valid thought".to_string(),
            confidence: 0.8,
        };
        assert!(LLMOutputParser::validate_draft(&valid_draft).is_ok());

        // Empty text
        let empty_draft = ThoughtNodeDraft {
            text: "".to_string(),
            confidence: 0.8,
        };
        assert!(LLMOutputParser::validate_draft(&empty_draft).is_err());

        // Invalid confidence
        let invalid_confidence_draft = ThoughtNodeDraft {
            text: "Valid text".to_string(),
            confidence: 1.5,
        };
        assert!(LLMOutputParser::validate_draft(&invalid_confidence_draft).is_err());

        // Too long text
        let long_draft = ThoughtNodeDraft {
            text: "a".repeat(1001),
            confidence: 0.8,
        };
        assert!(LLMOutputParser::validate_draft(&long_draft).is_err());
    }

    #[test]
    fn test_parse_thoughts_with_wrapped_text() {
        let completion = Completion::new(
            r#"Here are my thoughts:
        {"thoughts": [
            {"text": "First approach", "confidence": 0.85},
            {"text": "Alternative approach", "confidence": 0.65}
        ]}
        That's my analysis."#,
        );

        let drafts = LLMOutputParser::parse_thoughts(&completion).unwrap();
        assert_eq!(drafts.len(), 2);
        assert_eq!(drafts[0].text, "First approach");
        assert_eq!(drafts[0].confidence, 0.85);
    }
}
