use crate::ollama::OllamaClient;
use crate::parser::Parser;
use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Request to explain code
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExplainRequest {
    /// Path to the source file
    pub file_path: String,
    /// Optional specific function name to explain
    /// If None, explains the entire file structure
    pub function_name: Option<String>,
    /// Optional model override (defaults to qwen2.5-coder:3b)
    pub model: Option<String>,
}

/// Response containing the code explanation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExplainResponse {
    /// The explanation generated by Ollama
    pub explanation: String,
    /// The actual code that was explained
    pub code: String,
    /// Function signature if explaining a function
    pub signature: Option<String>,
    /// Start line number in file
    pub start_line: Option<usize>,
    /// End line number in file
    pub end_line: Option<usize>,
}

/// Code explainer that combines tree-sitter parsing with Ollama LLM
pub struct CodeExplainer {
    parser: Parser,
    ollama: OllamaClient,
}

impl CodeExplainer {
    /// Create a new code explainer with default Ollama configuration
    pub fn new() -> Result<Self> {
        let parser = Parser::new()?;
        let ollama = OllamaClient::new_default()?;
        Ok(Self { parser, ollama })
    }

    /// Create a new code explainer with custom Ollama model
    pub fn new_with_model(model: &str) -> Result<Self> {
        let parser = Parser::new()?;
        let config = crate::ollama::OllamaConfig {
            model: model.to_string(),
            ..Default::default()
        };
        let ollama = OllamaClient::new(config)?;
        Ok(Self { parser, ollama })
    }

    /// Explain code from a file
    ///
    /// If function_name is provided, extracts and explains that specific function.
    /// Otherwise, provides a high-level explanation of the file structure.
    pub fn explain(&self, request: &ExplainRequest) -> Result<ExplainResponse> {
        let file_path = Path::new(&request.file_path);

        // Verify file exists
        if !file_path.exists() {
            return Err(anyhow!("File not found: {}", request.file_path));
        }

        // Parse the file to get structure
        let structure = self.parser.parse_file(file_path)?;

        // If function name specified, find and explain that function
        if let Some(ref func_name) = request.function_name {
            self.explain_function(&structure, file_path, func_name)
        } else {
            self.explain_file(&structure, file_path)
        }
    }

    /// Explain a specific function
    fn explain_function(
        &self,
        structure: &crate::parser::CodeStructure,
        file_path: &Path,
        func_name: &str,
    ) -> Result<ExplainResponse> {
        // Find the function in the parsed structure
        let func_info = structure
            .functions
            .iter()
            .find(|f| f.name == func_name)
            .ok_or_else(|| anyhow!("Function '{}' not found in file", func_name))?;

        // Read the source file
        let source = std::fs::read_to_string(file_path)?;
        let lines: Vec<&str> = source.lines().collect();

        // Extract function code using line numbers
        let start_line = func_info.line_number;
        let end_line = func_info.end_line;

        if start_line == 0 || end_line == 0 || start_line > lines.len() || end_line > lines.len() {
            return Err(anyhow!(
                "Invalid line numbers for function: start={}, end={}",
                start_line,
                end_line
            ));
        }

        let function_code = lines[(start_line - 1)..end_line].join("\n");

        // Build function signature
        let signature = self.build_signature(func_info);

        // Build prompt for Ollama
        let prompt = format!(
            "Explain this {} function in 2-3 clear sentences. Focus on what it does, not how.\n\n\
             Function signature: {}\n\n\
             Code:\n{}\n\n\
             Explanation:",
            structure.language, signature, function_code
        );

        // Get explanation from Ollama
        let explanation = self
            .ollama
            .generate(&prompt)
            .map_err(|e| anyhow!("Failed to generate explanation: {}", e))?;

        Ok(ExplainResponse {
            explanation: explanation.trim().to_string(),
            code: function_code,
            signature: Some(signature),
            start_line: Some(start_line),
            end_line: Some(end_line),
        })
    }

    /// Explain an entire file's structure
    fn explain_file(
        &self,
        structure: &crate::parser::CodeStructure,
        _file_path: &Path,
    ) -> Result<ExplainResponse> {
        // Build summary of file structure
        let mut summary = String::new();
        summary.push_str(&format!("Language: {}\n", structure.language));
        summary.push_str(&format!("Functions: {}\n", structure.functions.len()));
        summary.push_str(&format!("Classes: {}\n", structure.classes.len()));
        summary.push_str(&format!("Imports: {}\n\n", structure.imports.len()));

        // List function signatures
        if !structure.functions.is_empty() {
            summary.push_str("Functions:\n");
            for func in &structure.functions {
                let sig = self.build_signature(func);
                summary.push_str(&format!("- {} (line {})\n", sig, func.line_number));
            }
        }

        // Build prompt for Ollama
        let prompt = format!(
            "Explain the purpose and structure of this {} source file in 3-4 sentences.\n\n\
             File structure:\n{}\n\n\
             Explanation:",
            structure.language, summary
        );

        // Get explanation from Ollama
        let explanation = self
            .ollama
            .generate(&prompt)
            .map_err(|e| anyhow!("Failed to generate explanation: {}", e))?;

        Ok(ExplainResponse {
            explanation: explanation.trim().to_string(),
            code: summary,
            signature: None,
            start_line: None,
            end_line: None,
        })
    }

    /// Build a function signature string from FunctionInfo
    fn build_signature(&self, func_info: &crate::parser::FunctionInfo) -> String {
        let params = func_info.parameters.join(", ");
        let return_type = func_info.return_type.as_deref().unwrap_or("void");

        if return_type == "void" || return_type.is_empty() {
            format!("{}({})", func_info.name, params)
        } else {
            format!("{}({}) -> {}", func_info.name, params, return_type)
        }
    }

    /// Get the underlying Ollama client (for testing)
    #[cfg(test)]
    pub fn ollama(&self) -> &OllamaClient {
        &self.ollama
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::NamedTempFile;

    fn create_test_rust_file() -> Result<NamedTempFile> {
        let file = tempfile::Builder::new().suffix(".rs").tempfile()?;
        let content = r#"
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}

pub fn multiply(x: i32, y: i32) -> i32 {
    x * y
}

fn helper_function() {
    println!("Helper");
}
"#;
        fs::write(file.path(), content)?;
        Ok(file)
    }

    #[test]
    fn test_explain_request_serialization() {
        let request = ExplainRequest {
            file_path: "test.rs".to_string(),
            function_name: Some("add".to_string()),
            model: None,
        };

        let serialized = serde_json::to_string(&request).unwrap();
        let deserialized: ExplainRequest = serde_json::from_str(&serialized).unwrap();

        assert_eq!(request.file_path, deserialized.file_path);
        assert_eq!(request.function_name, deserialized.function_name);
    }

    #[test]
    fn test_explain_response_serialization() {
        let response = ExplainResponse {
            explanation: "This function adds two numbers".to_string(),
            code: "fn add(a: i32, b: i32) -> i32 { a + b }".to_string(),
            signature: Some("add(a: i32, b: i32) -> i32".to_string()),
            start_line: Some(1),
            end_line: Some(3),
        };

        let serialized = serde_json::to_string(&response).unwrap();
        let deserialized: ExplainResponse = serde_json::from_str(&serialized).unwrap();

        assert_eq!(response.explanation, deserialized.explanation);
        assert_eq!(response.code, deserialized.code);
    }

    #[test]
    fn test_code_explainer_creation_fails_without_ollama() {
        // This test verifies that the explainer properly checks for Ollama
        let result = CodeExplainer::new();

        // Should either succeed (if ollama installed) or fail with proper error
        match result {
            Ok(_) => {
                // Ollama is installed, that's fine
            }
            Err(e) => {
                // Should fail with ollama-specific error
                assert!(e.to_string().contains("ollama"));
            }
        }
    }

    #[test]
    fn test_explain_request_with_nonexistent_file() -> Result<()> {
        // Skip if ollama not installed
        let explainer = match CodeExplainer::new() {
            Ok(e) => e,
            Err(_) => return Ok(()), // Skip test if ollama not available
        };

        let request = ExplainRequest {
            file_path: "/nonexistent/file.rs".to_string(),
            function_name: None,
            model: None,
        };

        let result = explainer.explain(&request);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("File not found"));

        Ok(())
    }

    #[test]
    fn test_explain_function_not_found() -> Result<()> {
        let test_file = create_test_rust_file()?;

        // Skip if ollama not installed
        let explainer = match CodeExplainer::new() {
            Ok(e) => e,
            Err(_) => return Ok(()), // Skip test if ollama not available
        };

        let request = ExplainRequest {
            file_path: test_file.path().to_str().unwrap().to_string(),
            function_name: Some("nonexistent_function".to_string()),
            model: None,
        };

        let result = explainer.explain(&request);
        assert!(result.is_err());
        let error_msg = result.unwrap_err().to_string();
        // Error message should contain either "not found" or "Function"
        assert!(
            error_msg.contains("not found") || error_msg.contains("Function"),
            "Expected error about function not found, got: {}",
            error_msg
        );

        Ok(())
    }

    #[test]
    #[ignore] // Only run when ollama is available
    fn test_explain_specific_function_integration() -> Result<()> {
        let test_file = create_test_rust_file()?;
        let explainer = CodeExplainer::new()?;

        let request = ExplainRequest {
            file_path: test_file.path().to_str().unwrap().to_string(),
            function_name: Some("add".to_string()),
            model: None,
        };

        let response = explainer.explain(&request)?;

        // Verify response structure
        assert!(!response.explanation.is_empty());
        assert!(response.code.contains("fn add"));
        assert!(response.signature.is_some());
        assert!(response.start_line.is_some());
        assert!(response.end_line.is_some());

        println!("Explanation: {}", response.explanation);
        println!("Code: {}", response.code);

        Ok(())
    }

    #[test]
    #[ignore] // Only run when ollama is available
    fn test_explain_entire_file_integration() -> Result<()> {
        let test_file = create_test_rust_file()?;
        let explainer = CodeExplainer::new()?;

        let request = ExplainRequest {
            file_path: test_file.path().to_str().unwrap().to_string(),
            function_name: None,
            model: None,
        };

        let response = explainer.explain(&request)?;

        // Verify response structure
        assert!(!response.explanation.is_empty());
        assert!(response.code.contains("Functions:"));
        assert!(response.signature.is_none());

        println!("File explanation: {}", response.explanation);

        Ok(())
    }

    #[test]
    fn test_code_explainer_with_custom_model() {
        let result = CodeExplainer::new_with_model("custom-model:7b");

        match result {
            Ok(explainer) => {
                assert_eq!(explainer.ollama().model(), "custom-model:7b");
            }
            Err(e) => {
                // Expected if ollama not installed
                assert!(e.to_string().contains("ollama"));
            }
        }
    }
}
