pub mod autonomy;
pub mod backup;
pub mod circuit_breaker;
pub mod cli;
pub mod code_directory_indexer;
pub mod code_explainer;
pub mod code_graph;
pub mod cognition;
pub mod cognitive;
pub mod cognitive_db;
pub mod common;
pub mod config;
pub mod db;
pub mod document_indexer;
pub mod global_store;
pub mod graph;
pub mod graph_cli;
pub mod graph_rebuilder;
pub mod http_stream_server;
pub mod intellitask;
pub mod intellitask_persistence;
pub mod logger;
pub mod macro_tools;
pub mod mcp;
pub mod mcp_server;
pub mod mcp_stdio;
pub mod memory;
pub mod memory_service;
pub mod message_bus;
pub mod meta_cognition;
pub mod metrics;
pub mod ollama;
pub mod parser;
pub mod portfolio;
pub mod project_analysis;
pub mod protocol;
pub mod raggraph;
pub mod router;
pub mod runtime;
pub mod schema_migration;
pub mod sequential;
pub mod storage;
pub mod tasks;
pub mod tools_cli;
pub mod vector;

// Re-export exact functions users requested
pub use cognitive_db::{recent_steps, store_step};
pub use mcp_server::run_mcp_stdio_server;
pub use mcp_stdio::run_stdio_server;
pub use tasks::{add_task, link_tasks, next_task, update_task};
pub use vector::{insert_text, search};
